import type { Certificate } from '../certificates/certificate.model';

export const certificates: Certificate[] = [
  {
    id: 'cert1',
    sessionId: 'ts1',
    participantId: 'p4',
    participantName: 'David Park',
    company: 'ByteWave',
    role: 'Developer',
    score: 97,
    completionDate: '2026-06-12',
    status: 'issued',
  },
  {
    id: 'cert2',
    sessionId: 'ts1',
    participantId: 'p10',
    participantName: 'Jack Brown',
    company: 'ByteWave',
    role: 'Manager',
    score: 91,
    completionDate: '2026-06-12',
    status: 'issued',
  },
  {
    id: 'cert3',
    sessionId: 'ts2',
    participantId: 'p3',
    participantName: 'Carol Kim',
    company: 'ByteWave',
    role: 'Designer',
    score: 94,
    completionDate: '2026-06-15',
    status: 'ready',
  },
  {
    id: 'cert4',
    sessionId: 'ts1',
    participantId: 'p1',
    participantName: 'Alice Chen',
    company: 'Acme Corp',
    role: 'Developer',
    score: 88,
    completionDate: '2026-06-15',
    status: 'ready',
  },
  {
    id: 'cert5',
    sessionId: 'ts1',
    participantId: 'p9',
    participantName: 'Iris Nakamura',
    company: 'Acme Corp',
    role: 'Analyst',
    score: 79,
    completionDate: '',
    status: 'pending',
  },
  {
    id: 'cert6',
    sessionId: 'ts2',
    participantId: 'p7',
    participantName: 'Grace Liu',
    company: 'DataPulse',
    role: 'Developer',
    score: 82,
    completionDate: '',
    status: 'pending',
  },
  {
    id: 'cert7',
    sessionId: 'ts1',
    participantId: 'p2',
    participantName: 'Bob Martinez',
    company: 'Acme Corp',
    role: 'Manager',
    score: 72,
    completionDate: '',
    status: 'pending',
  },
  {
    id: 'cert8',
    sessionId: 'ts2',
    participantId: 'p6',
    participantName: 'Frank Lee',
    company: 'Cloudify',
    role: 'Manager',
    score: 68,
    completionDate: '',
    status: 'pending',
  },
  {
    id: 'cert9',
    sessionId: 'ts2',
    participantId: 'p5',
    participantName: 'Emma Wilson',
    company: 'Cloudify',
    role: 'Analyst',
    score: 45,
    completionDate: '',
    status: 'pending',
  },
  {
    id: 'cert10',
    sessionId: 'ts3',
    participantId: 'p8',
    participantName: 'Henry Torres',
    company: 'DataPulse',
    role: 'Designer',
    score: 38,
    completionDate: '',
    status: 'pending',
  },
];
