import type { Material } from '../entities/material';

export const materials: Material[] = [
  {
    id: 'm1',
    title: 'Onboarding Guide v2.1',
    type: 'document',
    sizeKb: 842,
    status: 'ready',
    uploadedAt: '2026-05-10',
    owner: 'Admin',
  },
  {
    id: 'm2',
    title: 'Platform Walkthrough Video',
    type: 'video',
    sizeKb: 128400,
    status: 'ready',
    uploadedAt: '2026-05-12',
    owner: 'Training Team',
  },
  {
    id: 'm3',
    title: 'Security Compliance Deck',
    type: 'presentation',
    sizeKb: 3200,
    status: 'ready',
    uploadedAt: '2026-05-14',
    owner: 'Compliance',
  },
  {
    id: 'm4',
    title: 'Advanced Features Workbook',
    type: 'spreadsheet',
    sizeKb: 1100,
    status: 'draft',
    uploadedAt: '2026-05-20',
    owner: 'Admin',
  },
  {
    id: 'm5',
    title: 'Assessment Rubric',
    type: 'document',
    sizeKb: 540,
    status: 'review',
    uploadedAt: '2026-05-22',
    owner: 'Training Team',
  },
  {
    id: 'm6',
    title: 'API Reference Manual',
    type: 'document',
    sizeKb: 2300,
    status: 'ready',
    uploadedAt: '2026-05-08',
    owner: 'Engineering',
  },
  {
    id: 'm7',
    title: 'Q&A Session Recording',
    type: 'video',
    sizeKb: 95000,
    status: 'ready',
    uploadedAt: '2026-05-25',
    owner: 'Training Team',
  },
  {
    id: 'm8',
    title: 'Certification Criteria',
    type: 'document',
    sizeKb: 430,
    status: 'ready',
    uploadedAt: '2026-05-05',
    owner: 'Compliance',
  },
  {
    id: 'm9',
    title: 'Module Progress Tracker',
    type: 'spreadsheet',
    sizeKb: 680,
    status: 'draft',
    uploadedAt: '2026-06-01',
    owner: 'Admin',
  },
  {
    id: 'm10',
    title: 'Post-Training Survey',
    type: 'document',
    sizeKb: 320,
    status: 'review',
    uploadedAt: '2026-06-05',
    owner: 'Training Team',
  },
];
