import type { Participant, ModuleStatus } from '../participants/participant.model';

export const participants: Participant[] = [
  {
    id: 'p1',
    name: 'Alice Chen',
    company: 'Acme Corp',
    role: 'Developer',
    avatarColor: '#3b82f6',
    mods: [2, 2, 2, 1, 0] as ModuleStatus[],
    score: 88,
  },
  {
    id: 'p2',
    name: 'Bob Martinez',
    company: 'Acme Corp',
    role: 'Manager',
    avatarColor: '#8b5cf6',
    mods: [2, 2, 1, 0, 0] as ModuleStatus[],
    score: 72,
  },
  {
    id: 'p3',
    name: 'Carol Kim',
    company: 'ByteWave',
    role: 'Designer',
    avatarColor: '#ec4899',
    mods: [2, 2, 2, 2, 1] as ModuleStatus[],
    score: 94,
  },
  {
    id: 'p4',
    name: 'David Park',
    company: 'ByteWave',
    role: 'Developer',
    avatarColor: '#06b6d4',
    mods: [2, 2, 2, 2, 2] as ModuleStatus[],
    score: 97,
  },
  {
    id: 'p5',
    name: 'Emma Wilson',
    company: 'Cloudify',
    role: 'Analyst',
    avatarColor: '#f59e0b',
    mods: [2, 1, 0, 0, 0] as ModuleStatus[],
    score: 45,
  },
  {
    id: 'p6',
    name: 'Frank Lee',
    company: 'Cloudify',
    role: 'Manager',
    avatarColor: '#10b981',
    mods: [2, 2, 1, 1, 0] as ModuleStatus[],
    score: 68,
  },
  {
    id: 'p7',
    name: 'Grace Liu',
    company: 'DataPulse',
    role: 'Developer',
    avatarColor: '#ef4444',
    mods: [2, 2, 2, 1, 1] as ModuleStatus[],
    score: 82,
  },
  {
    id: 'p8',
    name: 'Henry Torres',
    company: 'DataPulse',
    role: 'Designer',
    avatarColor: '#14b8a6',
    mods: [1, 1, 0, 0, 0] as ModuleStatus[],
    score: 38,
  },
  {
    id: 'p9',
    name: 'Iris Nakamura',
    company: 'Acme Corp',
    role: 'Analyst',
    avatarColor: '#f97316',
    mods: [2, 2, 2, 2, 0] as ModuleStatus[],
    score: 79,
  },
  {
    id: 'p10',
    name: 'Jack Brown',
    company: 'ByteWave',
    role: 'Manager',
    avatarColor: '#6366f1',
    mods: [2, 2, 2, 2, 2] as ModuleStatus[],
    score: 91,
  },
];
