import type { ScheduleDay } from '../entities/schedule';

export const scheduleData: ScheduleDay[] = [
  {
    date: '2026-06-10',
    label: 'Day 1',
    status: 'completed',
    events: [
      {
        id: 'e1',
        time: '09:00',
        title: 'Kickoff & Introductions',
        type: 'session',
        tags: ['required'],
        presenter: 'Sarah Johnson',
        durationMin: 60,
      },
      {
        id: 'e2',
        time: '10:30',
        title: 'Onboarding Fundamentals',
        type: 'workshop',
        tags: ['required', 'recorded'],
        presenter: 'Training Team',
        durationMin: 90,
      },
      {
        id: 'e3',
        time: '13:00',
        title: 'Platform Overview Demo',
        type: 'session',
        tags: ['required', 'recorded'],
        presenter: 'Engineering',
        durationMin: 60,
      },
      {
        id: 'e4',
        time: '15:00',
        title: 'Open Q&A',
        type: 'office-hours',
        tags: ['optional'],
        durationMin: 45,
      },
    ],
  },
  {
    date: '2026-06-11',
    label: 'Day 2',
    status: 'completed',
    events: [
      {
        id: 'e5',
        time: '09:00',
        title: 'Security Compliance Module',
        type: 'session',
        tags: ['required', 'recorded'],
        presenter: 'Compliance',
        durationMin: 90,
      },
      {
        id: 'e6',
        time: '11:00',
        title: 'Compliance Assessment',
        type: 'assessment',
        tags: ['required'],
        durationMin: 45,
      },
      {
        id: 'e7',
        time: '14:00',
        title: 'Vendor Integration Workshop',
        type: 'workshop',
        tags: ['optional', 'external'],
        presenter: 'Partner Team',
        durationMin: 60,
      },
    ],
  },
  {
    date: '2026-06-12',
    label: 'Day 3',
    status: 'completed',
    events: [
      {
        id: 'e8',
        time: '09:00',
        title: 'Platform Walkthrough — Part 1',
        type: 'session',
        tags: ['required', 'recorded'],
        presenter: 'Training Team',
        durationMin: 75,
      },
      {
        id: 'e9',
        time: '10:30',
        title: 'Hands-On Lab',
        type: 'workshop',
        tags: ['required'],
        durationMin: 90,
      },
      {
        id: 'e10',
        time: '14:00',
        title: 'Platform Walkthrough — Part 2',
        type: 'session',
        tags: ['required', 'recorded'],
        presenter: 'Training Team',
        durationMin: 75,
      },
    ],
  },
  {
    date: '2026-06-13',
    label: 'Day 4',
    status: 'completed',
    events: [
      {
        id: 'e11',
        time: '09:00',
        title: 'Advanced Features Deep Dive',
        type: 'session',
        tags: ['required', 'recorded'],
        presenter: 'Engineering',
        durationMin: 120,
      },
      {
        id: 'e12',
        time: '13:00',
        title: 'Use Case Workshop',
        type: 'workshop',
        tags: ['required'],
        durationMin: 90,
      },
      {
        id: 'e13',
        time: '15:30',
        title: 'Industry Panel',
        type: 'session',
        tags: ['optional', 'external'],
        durationMin: 60,
      },
    ],
  },
  {
    date: '2026-06-15',
    label: 'Day 5',
    status: 'today',
    events: [
      {
        id: 'e14',
        time: '09:00',
        title: 'Final Assessment',
        type: 'assessment',
        tags: ['required'],
        durationMin: 60,
      },
      {
        id: 'e15',
        time: '11:00',
        title: 'Results Review & Feedback',
        type: 'session',
        tags: ['required'],
        presenter: 'Training Team',
        durationMin: 45,
      },
      {
        id: 'e16',
        time: '13:00',
        title: 'Advanced Office Hours',
        type: 'office-hours',
        tags: ['optional'],
        durationMin: 60,
      },
    ],
  },
  {
    date: '2026-06-16',
    label: 'Day 6',
    status: 'upcoming',
    events: [
      {
        id: 'e17',
        time: '09:00',
        title: 'Certification Ceremony',
        type: 'session',
        tags: ['required'],
        presenter: 'Leadership',
        durationMin: 60,
      },
      {
        id: 'e18',
        time: '11:00',
        title: 'Post-Training Survey',
        type: 'workshop',
        tags: ['required'],
        durationMin: 30,
      },
      {
        id: 'e19',
        time: '14:00',
        title: 'Alumni Network Intro',
        type: 'session',
        tags: ['optional', 'external'],
        durationMin: 45,
      },
    ],
  },
  {
    date: '2026-06-17',
    label: 'Day 7',
    status: 'upcoming',
    events: [
      {
        id: 'e20',
        time: '10:00',
        title: 'Manager Debrief',
        type: 'session',
        tags: ['required', 'external'],
        presenter: 'Sarah Johnson',
        durationMin: 60,
      },
      {
        id: 'e21',
        time: '13:00',
        title: 'Continuous Learning Paths Overview',
        type: 'session',
        tags: ['optional', 'recorded'],
        presenter: 'Training Team',
        durationMin: 45,
      },
    ],
  },
];
